development:
  adapter: postgresql
  encoding: utf8
  database: course_rank_development
  pool: 5
  host: localhost
  username: course_rank
  password: <%= ENV['RAILS_DB_PWD'] %>

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: course_rank_test
  pool: 5
  host: localhost
  username: course_rank
  password: <%= ENV['RAILS_DB_PWD'] %>

production:
  adapter: postgresql
  encoding: utf8
  database: course_rank
  pool: 5
  host: localhost
  username: course_rank
  password: <%= ENV['RAILS_DB_PWD'] %>

cucumber:
  <<: *TEST
